In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

In [2]:
# Punto 1

adult = pd.read_excel('/Users/pablotempone/Google Drive/Maestria/Redes Neuronales/Adult_Parte1.xlsx')

x = np.array(adult)

In [3]:
# Punto 2

x.shape

(11029, 4)

In [4]:
#3
x[:,:3].min(axis=0)

array([17,  1,  1])

In [5]:
#4
x[:,:3].max(axis=1)

array([55, 50, 34, ..., 50, 60, 43])

In [6]:
#5

x_scale = (x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))


In [7]:
#6
x_aleatorio = np.random.permutation(x_scale)

In [8]:
#7

T = x_scale[:,3]
X = x_scale[:,:3]

In [9]:
#8

rnd_nro = np.random.uniform(size=11029)

x_train = np.column_stack((X,rnd_nro))
x_train = x_train[x_train[:,3]<=0.8,:3]


x_test = np.column_stack((X,rnd_nro))
x_test = x_test[x_test[:,3]>0.8,:3]

T_train = np.column_stack((T,rnd_nro))
T_train = T_train[T_train[:,1]<=0.8,:1]

T_test = np.column_stack((T,rnd_nro))
T_test = T_test[T_test[:,1]>0.8,:1]

In [10]:
#9 

X_traspuesta = X.T

x_train_T = x_train.T

x_test_T = x_test.T
T_train_T = T_train.T
T_test_T = T_test.T

X_traspuesta.min(axis=1)

X_traspuesta.max(axis=0)

array([ 0.8       ,  0.8       ,  0.66666667, ...,  1.        ,
        0.8       ,  0.86666667])

In [11]:
#10

len(T_test)

prediction = np.random.randint(2, size=len(T_test))

In [12]:
#11

np.sum(prediction == T_test[:,0]) #1090 coincidencias

1112

In [13]:
#12

confusion_matrix(prediction,T_test[:,0])

array([[496, 581],
       [475, 616]])